USE [master]
GO
CREATE DATABASE [ProyectoPNTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProyectoPNTDB', FILENAME = N'C:\Users\alexu\ProyectoPNTDB.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProyectoPNTDB_log', FILENAME = N'C:\Users\alexu\ProyectoPNTDB_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ProyectoPNTDB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProyectoPNTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProyectoPNTDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ProyectoPNTDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProyectoPNTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProyectoPNTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProyectoPNTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProyectoPNTDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ProyectoPNTDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ProyectoPNTDB] SET  MULTI_USER 
GO
ALTER DATABASE [ProyectoPNTDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProyectoPNTDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProyectoPNTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProyectoPNTDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [ProyectoPNTDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articulos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[numeroArticulo] [int] NOT NULL,
	[precio] [float] NOT NULL,
	[descripcion] [nvarchar](max) NOT NULL,
	[nombre] [nvarchar](max) NOT NULL,
	[imagen] [nvarchar](max) NOT NULL,
	[stock] [int] NOT NULL,
	[talle] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Articulos] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carrito](
	[articuloId] [int] NOT NULL,
	[usuarioId] [int] NOT NULL,
 CONSTRAINT [PK_Carrito] PRIMARY KEY CLUSTERED 
(
	[articuloId] ASC,
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compras](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nroPedido] [int] NOT NULL,
	[fechaCompra] [datetime2](7) NOT NULL,
	[articuloId] [int] NOT NULL,
	[precioTotal] [float] NOT NULL,
 CONSTRAINT [PK_Compras] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListaArticulos](
	[articuloId] [int] NOT NULL,
	[compraId] [int] NOT NULL,
 CONSTRAINT [PK_ListaArticulos] PRIMARY KEY CLUSTERED 
(
	[articuloId] ASC,
	[compraId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListaCompras](
	[compraId] [int] NOT NULL,
	[usuarioId] [int] NOT NULL,
 CONSTRAINT [PK_ListaCompras] PRIMARY KEY CLUSTERED 
(
	[compraId] ASC,
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListaDeseados](
	[articuloId] [int] NOT NULL,
	[usuarioId] [int] NOT NULL,
 CONSTRAINT [PK_ListaDeseados] PRIMARY KEY CLUSTERED 
(
	[articuloId] ASC,
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombreUsuario] [nvarchar](max) NOT NULL,
	[nombreCompleto] [nvarchar](100) NOT NULL,
	[contraseña] [nvarchar](max) NOT NULL,
	[direccion] [nvarchar](max) NOT NULL,
	[mail] [nvarchar](max) NOT NULL,
	[carritoId] [int] NOT NULL,
	[deseadosId] [int] NOT NULL,
	[ComprasId] [int] NOT NULL,
	[tipoUsuario] [int] NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Carrito_usuarioId] ON [dbo].[Carrito]
(
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ListaArticulos_compraId] ON [dbo].[ListaArticulos]
(
	[compraId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ListaCompras_usuarioId] ON [dbo].[ListaCompras]
(
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ListaDeseados_usuarioId] ON [dbo].[ListaDeseados]
(
	[usuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Carrito]  WITH CHECK ADD  CONSTRAINT [FK_Carrito_Articulos_articuloId] FOREIGN KEY([articuloId])
REFERENCES [dbo].[Articulos] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Carrito] CHECK CONSTRAINT [FK_Carrito_Articulos_articuloId]
GO
ALTER TABLE [dbo].[Carrito]  WITH CHECK ADD  CONSTRAINT [FK_Carrito_Usuarios_usuarioId] FOREIGN KEY([usuarioId])
REFERENCES [dbo].[Usuarios] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Carrito] CHECK CONSTRAINT [FK_Carrito_Usuarios_usuarioId]
GO
ALTER TABLE [dbo].[ListaArticulos]  WITH CHECK ADD  CONSTRAINT [FK_ListaArticulos_Articulos_articuloId] FOREIGN KEY([articuloId])
REFERENCES [dbo].[Articulos] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaArticulos] CHECK CONSTRAINT [FK_ListaArticulos_Articulos_articuloId]
GO
ALTER TABLE [dbo].[ListaArticulos]  WITH CHECK ADD  CONSTRAINT [FK_ListaArticulos_Compras_compraId] FOREIGN KEY([compraId])
REFERENCES [dbo].[Compras] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaArticulos] CHECK CONSTRAINT [FK_ListaArticulos_Compras_compraId]
GO
ALTER TABLE [dbo].[ListaCompras]  WITH CHECK ADD  CONSTRAINT [FK_ListaCompras_Compras_compraId] FOREIGN KEY([compraId])
REFERENCES [dbo].[Compras] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaCompras] CHECK CONSTRAINT [FK_ListaCompras_Compras_compraId]
GO
ALTER TABLE [dbo].[ListaCompras]  WITH CHECK ADD  CONSTRAINT [FK_ListaCompras_Usuarios_usuarioId] FOREIGN KEY([usuarioId])
REFERENCES [dbo].[Usuarios] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaCompras] CHECK CONSTRAINT [FK_ListaCompras_Usuarios_usuarioId]
GO
ALTER TABLE [dbo].[ListaDeseados]  WITH CHECK ADD  CONSTRAINT [FK_ListaDeseados_Articulos_articuloId] FOREIGN KEY([articuloId])
REFERENCES [dbo].[Articulos] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaDeseados] CHECK CONSTRAINT [FK_ListaDeseados_Articulos_articuloId]
GO
ALTER TABLE [dbo].[ListaDeseados]  WITH CHECK ADD  CONSTRAINT [FK_ListaDeseados_Usuarios_usuarioId] FOREIGN KEY([usuarioId])
REFERENCES [dbo].[Usuarios] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListaDeseados] CHECK CONSTRAINT [FK_ListaDeseados_Usuarios_usuarioId]
GO
USE [master]
GO
ALTER DATABASE [ProyectoPNTDB] SET  READ_WRITE 
GO
